### PR TITLE
Update indentation from 4 to 2 spaces

### PR DESCRIPTION
**Pull request by peripateticus**
This PR updates REI's JavaScript indentation from 4 to 2 spaces.

Why?
* 2 spaces sufficiently conveys that you are in a new block while additionally preserving valuable horizontal real estate.
* We are more in sync with industry and GitHub project styles and guides.

### CODE REVIEW

**Comment by bonpixel** [comment]
oh mah gersh!!!

**Comment by bonpixel** [comment]
I would ❤️  the two space but I'm not too zealous about it.

**Comment by peripateticus** [comment]
@bonpixel I totally understand. I think the question really is, if you love it and most of our team feels the same way (which we can only know via our team vote), why are we not doing it? If, as a team, we are tolerating our style guide (i.e. most of us think "I don't get style x but that's just the way it is here at REI"), something is very wrong. Style evolves as developers evolve. Yes, style is not a personal preference which is why we put any changes up to a vote. As a team, we should not be constrained by our style guide and we its our obligation to make it work for us.

**Comment by Neogavin** [comment]
Could we review this in the next team meeting?  I'm not too sure how I feel about this.

**Comment by bonpixel** [comment]
@peripateticus Style guides are good servants but hateful masters. 

I agree with your points. At the end of the day this thing exists to make things "better". Better is sometimes subjective, but let's not get caught up in the emotion of it and figure out what works best for the team. 

It seems that more generally as a team we need to come to consensus as to the "how" (meaning how is it implemented) as opposed to the "what/why". ANY changes always seem painful, but they really shouldn't be.

**Comment by debugish** [comment]
Closing, went through the process and after a team vote there is a preference towards 4 spaces.

**Pull request closed without merging**
